version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_localhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - php
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_localhost
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"